<?php
/**
 * ConfigMinimalResponseData
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Convert API for Experiences Serving
 *
 * Serve and track experiences to your users using Convert APIs and tools
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ConfigMinimalResponseData Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ConfigMinimalResponseData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ConfigMinimalResponseData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'include_jquery' => 'bool',
        'include_jquery_v1' => 'bool',
        'disable_spa_functionality' => 'bool',
        'version' => 'string',
        'tracking_script' => '\OpenAPI\Client\Model\TrackingScriptReleaseBase',
        'account_id' => 'string',
        'project_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'include_jquery' => null,
        'include_jquery_v1' => null,
        'disable_spa_functionality' => null,
        'version' => null,
        'tracking_script' => null,
        'account_id' => null,
        'project_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'include_jquery' => false,
        'include_jquery_v1' => false,
        'disable_spa_functionality' => false,
        'version' => true,
        'tracking_script' => true,
        'account_id' => false,
        'project_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'include_jquery' => 'include_jquery',
        'include_jquery_v1' => 'include_jquery_v1',
        'disable_spa_functionality' => 'disable_spa_functionality',
        'version' => 'version',
        'tracking_script' => 'tracking_script',
        'account_id' => 'account_id',
        'project_id' => 'project_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'include_jquery' => 'setIncludeJquery',
        'include_jquery_v1' => 'setIncludeJqueryV1',
        'disable_spa_functionality' => 'setDisableSpaFunctionality',
        'version' => 'setVersion',
        'tracking_script' => 'setTrackingScript',
        'account_id' => 'setAccountId',
        'project_id' => 'setProjectId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'include_jquery' => 'getIncludeJquery',
        'include_jquery_v1' => 'getIncludeJqueryV1',
        'disable_spa_functionality' => 'getDisableSpaFunctionality',
        'version' => 'getVersion',
        'tracking_script' => 'getTrackingScript',
        'account_id' => 'getAccountId',
        'project_id' => 'getProjectId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('include_jquery', $data ?? [], null);
        $this->setIfExists('include_jquery_v1', $data ?? [], false);
        $this->setIfExists('disable_spa_functionality', $data ?? [], false);
        $this->setIfExists('version', $data ?? [], null);
        $this->setIfExists('tracking_script', $data ?? [], null);
        $this->setIfExists('account_id', $data ?? [], null);
        $this->setIfExists('project_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['version']) && (mb_strlen($this->container['version']) > 50)) {
            $invalidProperties[] = "invalid value for 'version', the character length must be smaller than or equal to 50.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets include_jquery
     *
     * @return bool|null
     */
    public function getIncludeJquery()
    {
        return $this->container['include_jquery'];
    }

    /**
     * Sets include_jquery
     *
     * @param bool|null $include_jquery Whether to include jQuery library or not into the javascript tracking file served by Convert and loaded via the tracking snippet. If jQuery is not included, it has to be loaded on page, before Convert's tracking code
     *
     * @return self
     */
    public function setIncludeJquery($include_jquery)
    {
        if (is_null($include_jquery)) {
            throw new \InvalidArgumentException('non-nullable include_jquery cannot be null');
        }
        $this->container['include_jquery'] = $include_jquery;

        return $this;
    }

    /**
     * Gets include_jquery_v1
     *
     * @return bool|null
     */
    public function getIncludeJqueryV1()
    {
        return $this->container['include_jquery_v1'];
    }

    /**
     * Sets include_jquery_v1
     *
     * @param bool|null $include_jquery_v1 Whether to include jQuery library or not into the v1 javascript tracking file served by Convert and loaded via the tracking snippet.
     *
     * @return self
     */
    public function setIncludeJqueryV1($include_jquery_v1)
    {
        if (is_null($include_jquery_v1)) {
            throw new \InvalidArgumentException('non-nullable include_jquery_v1 cannot be null');
        }
        $this->container['include_jquery_v1'] = $include_jquery_v1;

        return $this;
    }

    /**
     * Gets disable_spa_functionality
     *
     * @return bool|null
     */
    public function getDisableSpaFunctionality()
    {
        return $this->container['disable_spa_functionality'];
    }

    /**
     * Sets disable_spa_functionality
     *
     * @param bool|null $disable_spa_functionality Whether to disable the SPA (Single Page Application) related functionalities from the tracking scripts V1. Most websites work fine without disabling SPA functionality regardless of the fact they are Single Page Apps or not. In edge situation, this setting might prove handy
     *
     * @return self
     */
    public function setDisableSpaFunctionality($disable_spa_functionality)
    {
        if (is_null($disable_spa_functionality)) {
            throw new \InvalidArgumentException('non-nullable disable_spa_functionality cannot be null');
        }
        $this->container['disable_spa_functionality'] = $disable_spa_functionality;

        return $this;
    }

    /**
     * Gets version
     *
     * @return string|null
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param string|null $version Tracks the project's version, updated with each change done inside the project, which would affect the config of that project. The format is [ISO_datetime]-[incremental_number].
     *
     * @return self
     */
    public function setVersion($version)
    {
        if (is_null($version)) {
            array_push($this->openAPINullablesSetToNull, 'version');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('version', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($version) && (mb_strlen($version) > 50)) {
            throw new \InvalidArgumentException('invalid length for $version when calling ConfigMinimalResponseData., must be smaller than or equal to 50.');
        }

        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets tracking_script
     *
     * @return \OpenAPI\Client\Model\TrackingScriptReleaseBase|null
     */
    public function getTrackingScript()
    {
        return $this->container['tracking_script'];
    }

    /**
     * Sets tracking_script
     *
     * @param \OpenAPI\Client\Model\TrackingScriptReleaseBase|null $tracking_script tracking_script
     *
     * @return self
     */
    public function setTrackingScript($tracking_script)
    {
        if (is_null($tracking_script)) {
            array_push($this->openAPINullablesSetToNull, 'tracking_script');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tracking_script', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tracking_script'] = $tracking_script;

        return $this;
    }

    /**
     * Gets account_id
     *
     * @return string|null
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     *
     * @param string|null $account_id Account ID
     *
     * @return self
     */
    public function setAccountId($account_id)
    {
        if (is_null($account_id)) {
            throw new \InvalidArgumentException('non-nullable account_id cannot be null');
        }
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets project_id
     *
     * @return string|null
     */
    public function getProjectId()
    {
        return $this->container['project_id'];
    }

    /**
     * Sets project_id
     *
     * @param string|null $project_id Project ID
     *
     * @return self
     */
    public function setProjectId($project_id)
    {
        if (is_null($project_id)) {
            throw new \InvalidArgumentException('non-nullable project_id cannot be null');
        }
        $this->container['project_id'] = $project_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


