<?php
/**
 * ConfigExperience
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Convert API for Experiences Serving
 *
 * Serve and track experiences to your users using Convert APIs and tools
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ConfigExperience Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ConfigExperience implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ConfigExperience';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'name' => 'string',
        'key' => 'string',
        'locations' => 'string[]',
        'site_area' => '\OpenAPI\Client\Model\RuleObject',
        'audiences' => 'string[]',
        'goals' => 'string[]',
        'multipage_pages' => '\OpenAPI\Client\Model\MultipageExperiencePage[]',
        'status' => '\OpenAPI\Client\Model\ExperienceStatuses',
        'global_js' => 'string',
        'global_css' => 'string',
        'type' => '\OpenAPI\Client\Model\ExperienceTypes',
        'version' => 'float',
        'variations' => '\OpenAPI\Client\Model\ExperienceVariationConfig[]',
        'integrations' => '\OpenAPI\Client\Model\ConfigExperienceIntegrationsInner[]',
        'environments' => 'string[]',
        'environment' => 'string',
        'settings' => '\OpenAPI\Client\Model\ConfigExperienceSettings'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'name' => null,
        'key' => null,
        'locations' => null,
        'site_area' => null,
        'audiences' => null,
        'goals' => null,
        'multipage_pages' => null,
        'status' => null,
        'global_js' => null,
        'global_css' => null,
        'type' => null,
        'version' => null,
        'variations' => null,
        'integrations' => null,
        'environments' => null,
        'environment' => null,
        'settings' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'key' => false,
        'locations' => true,
        'site_area' => true,
        'audiences' => true,
        'goals' => false,
        'multipage_pages' => false,
        'status' => false,
        'global_js' => false,
        'global_css' => false,
        'type' => false,
        'version' => false,
        'variations' => false,
        'integrations' => false,
        'environments' => false,
        'environment' => false,
        'settings' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'key' => 'key',
        'locations' => 'locations',
        'site_area' => 'site_area',
        'audiences' => 'audiences',
        'goals' => 'goals',
        'multipage_pages' => 'multipage_pages',
        'status' => 'status',
        'global_js' => 'global_js',
        'global_css' => 'global_css',
        'type' => 'type',
        'version' => 'version',
        'variations' => 'variations',
        'integrations' => 'integrations',
        'environments' => 'environments',
        'environment' => 'environment',
        'settings' => 'settings'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'key' => 'setKey',
        'locations' => 'setLocations',
        'site_area' => 'setSiteArea',
        'audiences' => 'setAudiences',
        'goals' => 'setGoals',
        'multipage_pages' => 'setMultipagePages',
        'status' => 'setStatus',
        'global_js' => 'setGlobalJs',
        'global_css' => 'setGlobalCss',
        'type' => 'setType',
        'version' => 'setVersion',
        'variations' => 'setVariations',
        'integrations' => 'setIntegrations',
        'environments' => 'setEnvironments',
        'environment' => 'setEnvironment',
        'settings' => 'setSettings'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'key' => 'getKey',
        'locations' => 'getLocations',
        'site_area' => 'getSiteArea',
        'audiences' => 'getAudiences',
        'goals' => 'getGoals',
        'multipage_pages' => 'getMultipagePages',
        'status' => 'getStatus',
        'global_js' => 'getGlobalJs',
        'global_css' => 'getGlobalCss',
        'type' => 'getType',
        'version' => 'getVersion',
        'variations' => 'getVariations',
        'integrations' => 'getIntegrations',
        'environments' => 'getEnvironments',
        'environment' => 'getEnvironment',
        'settings' => 'getSettings'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('key', $data ?? [], null);
        $this->setIfExists('locations', $data ?? [], null);
        $this->setIfExists('site_area', $data ?? [], null);
        $this->setIfExists('audiences', $data ?? [], null);
        $this->setIfExists('goals', $data ?? [], null);
        $this->setIfExists('multipage_pages', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('global_js', $data ?? [], null);
        $this->setIfExists('global_css', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('version', $data ?? [], null);
        $this->setIfExists('variations', $data ?? [], null);
        $this->setIfExists('integrations', $data ?? [], null);
        $this->setIfExists('environments', $data ?? [], null);
        $this->setIfExists('environment', $data ?? [], null);
        $this->setIfExists('settings', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id Experience ID
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Experience Name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets key
     *
     * @return string|null
     */
    public function getKey()
    {
        return $this->container['key'];
    }

    /**
     * Sets key
     *
     * @param string|null $key Experience readable key that uniquely identifies this experience
     *
     * @return self
     */
    public function setKey($key)
    {
        if (is_null($key)) {
            throw new \InvalidArgumentException('non-nullable key cannot be null');
        }
        $this->container['key'] = $key;

        return $this;
    }

    /**
     * Gets locations
     *
     * @return string[]|null
     */
    public function getLocations()
    {
        return $this->container['locations'];
    }

    /**
     * Sets locations
     *
     * @param string[]|null $locations List of locations IDs on which this experience is presented. Either this or **site_area** is given but should not be both.
     *
     * @return self
     */
    public function setLocations($locations)
    {
        if (is_null($locations)) {
            array_push($this->openAPINullablesSetToNull, 'locations');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('locations', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['locations'] = $locations;

        return $this;
    }

    /**
     * Gets site_area
     *
     * @return \OpenAPI\Client\Model\RuleObject|null
     */
    public function getSiteArea()
    {
        return $this->container['site_area'];
    }

    /**
     * Sets site_area
     *
     * @param \OpenAPI\Client\Model\RuleObject|null $site_area Rules that define where the experience is gonna run. Either this or **locations** is given but should not be both.
     *
     * @return self
     */
    public function setSiteArea($site_area)
    {
        if (is_null($site_area)) {
            array_push($this->openAPINullablesSetToNull, 'site_area');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('site_area', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['site_area'] = $site_area;

        return $this;
    }

    /**
     * Gets audiences
     *
     * @return string[]|null
     */
    public function getAudiences()
    {
        return $this->container['audiences'];
    }

    /**
     * Sets audiences
     *
     * @param string[]|null $audiences List of audiences IDs to which this experience is presented to
     *
     * @return self
     */
    public function setAudiences($audiences)
    {
        if (is_null($audiences)) {
            array_push($this->openAPINullablesSetToNull, 'audiences');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('audiences', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['audiences'] = $audiences;

        return $this;
    }

    /**
     * Gets goals
     *
     * @return string[]|null
     */
    public function getGoals()
    {
        return $this->container['goals'];
    }

    /**
     * Sets goals
     *
     * @param string[]|null $goals List of goals IDs to which will be tracked for this experience
     *
     * @return self
     */
    public function setGoals($goals)
    {
        if (is_null($goals)) {
            throw new \InvalidArgumentException('non-nullable goals cannot be null');
        }
        $this->container['goals'] = $goals;

        return $this;
    }

    /**
     * Gets multipage_pages
     *
     * @return \OpenAPI\Client\Model\MultipageExperiencePage[]|null
     */
    public function getMultipagePages()
    {
        return $this->container['multipage_pages'];
    }

    /**
     * Sets multipage_pages
     *
     * @param \OpenAPI\Client\Model\MultipageExperiencePage[]|null $multipage_pages Only for multipage experience type
     *
     * @return self
     */
    public function setMultipagePages($multipage_pages)
    {
        if (is_null($multipage_pages)) {
            throw new \InvalidArgumentException('non-nullable multipage_pages cannot be null');
        }
        $this->container['multipage_pages'] = $multipage_pages;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \OpenAPI\Client\Model\ExperienceStatuses|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \OpenAPI\Client\Model\ExperienceStatuses|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets global_js
     *
     * @return string|null
     */
    public function getGlobalJs()
    {
        return $this->container['global_js'];
    }

    /**
     * Sets global_js
     *
     * @param string|null $global_js Global Experience's JavaScript that will run for this experience before its changes are applied
     *
     * @return self
     */
    public function setGlobalJs($global_js)
    {
        if (is_null($global_js)) {
            throw new \InvalidArgumentException('non-nullable global_js cannot be null');
        }
        $this->container['global_js'] = $global_js;

        return $this;
    }

    /**
     * Gets global_css
     *
     * @return string|null
     */
    public function getGlobalCss()
    {
        return $this->container['global_css'];
    }

    /**
     * Sets global_css
     *
     * @param string|null $global_css Global Experience's StyleSheet that will run for this experience before its changes are applied
     *
     * @return self
     */
    public function setGlobalCss($global_css)
    {
        if (is_null($global_css)) {
            throw new \InvalidArgumentException('non-nullable global_css cannot be null');
        }
        $this->container['global_css'] = $global_css;

        return $this;
    }

    /**
     * Gets type
     *
     * @return \OpenAPI\Client\Model\ExperienceTypes|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \OpenAPI\Client\Model\ExperienceTypes|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets version
     *
     * @return float|null
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param float|null $version Experience's version number
     *
     * @return self
     */
    public function setVersion($version)
    {
        if (is_null($version)) {
            throw new \InvalidArgumentException('non-nullable version cannot be null');
        }
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets variations
     *
     * @return \OpenAPI\Client\Model\ExperienceVariationConfig[]|null
     */
    public function getVariations()
    {
        return $this->container['variations'];
    }

    /**
     * Sets variations
     *
     * @param \OpenAPI\Client\Model\ExperienceVariationConfig[]|null $variations Experience's variations list
     *
     * @return self
     */
    public function setVariations($variations)
    {
        if (is_null($variations)) {
            throw new \InvalidArgumentException('non-nullable variations cannot be null');
        }
        $this->container['variations'] = $variations;

        return $this;
    }

    /**
     * Gets integrations
     *
     * @return \OpenAPI\Client\Model\ConfigExperienceIntegrationsInner[]|null
     */
    public function getIntegrations()
    {
        return $this->container['integrations'];
    }

    /**
     * Sets integrations
     *
     * @param \OpenAPI\Client\Model\ConfigExperienceIntegrationsInner[]|null $integrations List of integrations that this experience's data is sent to
     *
     * @return self
     */
    public function setIntegrations($integrations)
    {
        if (is_null($integrations)) {
            throw new \InvalidArgumentException('non-nullable integrations cannot be null');
        }
        $this->container['integrations'] = $integrations;

        return $this;
    }

    /**
     * Gets environments
     *
     * @return string[]|null
     * @deprecated
     */
    public function getEnvironments()
    {
        return $this->container['environments'];
    }

    /**
     * Sets environments
     *
     * @param string[]|null $environments List of environments that this experience is supposed to run on. The full list of available environments is defined at  project level. If this list is empty, the experience will run on all environments.
     *
     * @return self
     * @deprecated
     */
    public function setEnvironments($environments)
    {
        if (is_null($environments)) {
            throw new \InvalidArgumentException('non-nullable environments cannot be null');
        }
        $this->container['environments'] = $environments;

        return $this;
    }

    /**
     * Gets environment
     *
     * @return string|null
     */
    public function getEnvironment()
    {
        return $this->container['environment'];
    }

    /**
     * Sets environment
     *
     * @param string|null $environment The environment where this experience will run. It has to be one of the environments defined at the project level
     *
     * @return self
     */
    public function setEnvironment($environment)
    {
        if (is_null($environment)) {
            throw new \InvalidArgumentException('non-nullable environment cannot be null');
        }
        $this->container['environment'] = $environment;

        return $this;
    }

    /**
     * Gets settings
     *
     * @return \OpenAPI\Client\Model\ConfigExperienceSettings|null
     */
    public function getSettings()
    {
        return $this->container['settings'];
    }

    /**
     * Sets settings
     *
     * @param \OpenAPI\Client\Model\ConfigExperienceSettings|null $settings settings
     *
     * @return self
     */
    public function setSettings($settings)
    {
        if (is_null($settings)) {
            throw new \InvalidArgumentException('non-nullable settings cannot be null');
        }
        $this->container['settings'] = $settings;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


