<?php
/**
 * ExperienceTypes
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Convert API for Experiences Serving
 *
 * Serve and track experiences to your users using Convert APIs and tools
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ExperienceTypes Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ExperienceTypes
{
    /**
     * Possible values of this enum
     */
    public const A_B = 'a/b';

    public const A_B_FULLSTACK = 'a/b_fullstack';

    public const A_A = 'a/a';

    public const MVT = 'mvt';

    public const SPLIT_URL = 'split_url';

    public const MULTIPAGE = 'multipage';

    public const DEPLOY = 'deploy';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::A_B,
            self::A_B_FULLSTACK,
            self::A_A,
            self::MVT,
            self::SPLIT_URL,
            self::MULTIPAGE,
            self::DEPLOY
        ];
    }
}


