<?php
/**
 * LocationTriggerTypes
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Convert API for Experiences Serving
 *
 * Serve and track experiences to your users using Convert APIs and tools
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * LocationTriggerTypes Class Doc Comment
 *
 * @category Class
 * @description Describes possible location trigger types. Note that &#x60;upon_run&#x60; is always the case for **fullstack** projects.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LocationTriggerTypes
{
    /**
     * Possible values of this enum
     */
    public const UPON_RUN = 'upon_run';

    public const MANUAL = 'manual';

    public const DOM_ELEMENT = 'dom_element';

    public const CALLBACK = 'callback';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UPON_RUN,
            self::MANUAL,
            self::DOM_ELEMENT,
            self::CALLBACK
        ];
    }
}


