<?php
/**
 * MinuteOfHourMatchRulesTypes
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Convert API for Experiences Serving
 *
 * Serve and track experiences to your users using Convert APIs and tools
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * MinuteOfHourMatchRulesTypes Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MinuteOfHourMatchRulesTypes
{
    /**
     * Possible values of this enum
     */
    public const LOCAL_TIME_MINUTE_OF_HOUR = 'local_time_minute_of_hour';

    public const PROJECT_TIME_MINUTE_OF_HOUR = 'project_time_minute_of_hour';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::LOCAL_TIME_MINUTE_OF_HOUR,
            self::PROJECT_TIME_MINUTE_OF_HOUR
        ];
    }
}


