<?php
/**
 * TextMatchRulesTypes
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Convert API for Experiences Serving
 *
 * Serve and track experiences to your users using Convert APIs and tools
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * TextMatchRulesTypes Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TextMatchRulesTypes
{
    /**
     * Possible values of this enum
     */
    public const URL = 'url';

    public const URL_WITH_QUERY = 'url_with_query';

    public const QUERY_STRING = 'query_string';

    public const CAMPAIGN = 'campaign';

    public const KEYWORD = 'keyword';

    public const MEDIUM = 'medium';

    public const SOURCE_NAME = 'source_name';

    public const CITY = 'city';

    public const REGION = 'region';

    public const BROWSER_VERSION = 'browser_version';

    public const USER_AGENT = 'user_agent';

    public const PAGE_TAG_PAGE_TYPE = 'page_tag_page_type';

    public const PAGE_TAG_CATEGORY_ID = 'page_tag_category_id';

    public const PAGE_TAG_CATEGORY_NAME = 'page_tag_category_name';

    public const PAGE_TAG_PRODUCT_SKU = 'page_tag_product_sku';

    public const PAGE_TAG_PRODUCT_NAME = 'page_tag_product_name';

    public const PAGE_TAG_CUSTOMER_ID = 'page_tag_customer_id';

    public const PAGE_TAG_CUSTOM_1 = 'page_tag_custom_1';

    public const PAGE_TAG_CUSTOM_2 = 'page_tag_custom_2';

    public const PAGE_TAG_CUSTOM_3 = 'page_tag_custom_3';

    public const PAGE_TAG_CUSTOM_4 = 'page_tag_custom_4';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::URL,
            self::URL_WITH_QUERY,
            self::QUERY_STRING,
            self::CAMPAIGN,
            self::KEYWORD,
            self::MEDIUM,
            self::SOURCE_NAME,
            self::CITY,
            self::REGION,
            self::BROWSER_VERSION,
            self::USER_AGENT,
            self::PAGE_TAG_PAGE_TYPE,
            self::PAGE_TAG_CATEGORY_ID,
            self::PAGE_TAG_CATEGORY_NAME,
            self::PAGE_TAG_PRODUCT_SKU,
            self::PAGE_TAG_PRODUCT_NAME,
            self::PAGE_TAG_CUSTOMER_ID,
            self::PAGE_TAG_CUSTOM_1,
            self::PAGE_TAG_CUSTOM_2,
            self::PAGE_TAG_CUSTOM_3,
            self::PAGE_TAG_CUSTOM_4
        ];
    }
}


