<?php
/**
 * VisitorSegments
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Convert API for Experiences Serving
 *
 * Serve and track experiences to your users using Convert APIs and tools
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * VisitorSegments Class Doc Comment
 *
 * @category Class
 * @description Segments under which this visitor is placed. Some defaults keys are accepted and any other free field **key value** could be used for fullstack projects
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class VisitorSegments implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'VisitorSegments';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'browser' => 'string',
        'devices' => 'string[]',
        'source' => 'string',
        'campaign' => 'string',
        'visitor_type' => 'string',
        'country' => 'string',
        'custom_segments' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'browser' => null,
        'devices' => null,
        'source' => null,
        'campaign' => null,
        'visitor_type' => null,
        'country' => null,
        'custom_segments' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'browser' => false,
        'devices' => false,
        'source' => false,
        'campaign' => false,
        'visitor_type' => false,
        'country' => false,
        'custom_segments' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'browser' => 'browser',
        'devices' => 'devices',
        'source' => 'source',
        'campaign' => 'campaign',
        'visitor_type' => 'visitorType',
        'country' => 'country',
        'custom_segments' => 'custom_segments'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'browser' => 'setBrowser',
        'devices' => 'setDevices',
        'source' => 'setSource',
        'campaign' => 'setCampaign',
        'visitor_type' => 'setVisitorType',
        'country' => 'setCountry',
        'custom_segments' => 'setCustomSegments'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'browser' => 'getBrowser',
        'devices' => 'getDevices',
        'source' => 'getSource',
        'campaign' => 'getCampaign',
        'visitor_type' => 'getVisitorType',
        'country' => 'getCountry',
        'custom_segments' => 'getCustomSegments'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const BROWSER_IE = 'IE';
    public const BROWSER_CH = 'CH';
    public const BROWSER_FF = 'FF';
    public const BROWSER_OP = 'OP';
    public const BROWSER_SF = 'SF';
    public const BROWSER_OTH = 'OTH';
    public const DEVICES_ALLPH = 'ALLPH';
    public const DEVICES_IPH = 'IPH';
    public const DEVICES_OTHPH = 'OTHPH';
    public const DEVICES_ALLTAB = 'ALLTAB';
    public const DEVICES_IPAD = 'IPAD';
    public const DEVICES_OTHTAB = 'OTHTAB';
    public const DEVICES_DESK = 'DESK';
    public const DEVICES_OTHDEV = 'OTHDEV';
    public const SOURCE_CAMPAIGN = 'campaign';
    public const SOURCE_SEARCH = 'search';
    public const SOURCE_REFERRAL = 'referral';
    public const SOURCE_DIRECT = 'direct';
    public const VISITOR_TYPE__NEW = 'new';
    public const VISITOR_TYPE_RETURNING = 'returning';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBrowserAllowableValues()
    {
        return [
            self::BROWSER_IE,
            self::BROWSER_CH,
            self::BROWSER_FF,
            self::BROWSER_OP,
            self::BROWSER_SF,
            self::BROWSER_OTH,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDevicesAllowableValues()
    {
        return [
            self::DEVICES_ALLPH,
            self::DEVICES_IPH,
            self::DEVICES_OTHPH,
            self::DEVICES_ALLTAB,
            self::DEVICES_IPAD,
            self::DEVICES_OTHTAB,
            self::DEVICES_DESK,
            self::DEVICES_OTHDEV,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSourceAllowableValues()
    {
        return [
            self::SOURCE_CAMPAIGN,
            self::SOURCE_SEARCH,
            self::SOURCE_REFERRAL,
            self::SOURCE_DIRECT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getVisitorTypeAllowableValues()
    {
        return [
            self::VISITOR_TYPE__NEW,
            self::VISITOR_TYPE_RETURNING,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('browser', $data ?? [], null);
        $this->setIfExists('devices', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
        $this->setIfExists('campaign', $data ?? [], null);
        $this->setIfExists('visitor_type', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('custom_segments', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getBrowserAllowableValues();
        if (!is_null($this->container['browser']) && !in_array($this->container['browser'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'browser', must be one of '%s'",
                $this->container['browser'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSourceAllowableValues();
        if (!is_null($this->container['source']) && !in_array($this->container['source'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'source', must be one of '%s'",
                $this->container['source'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getVisitorTypeAllowableValues();
        if (!is_null($this->container['visitor_type']) && !in_array($this->container['visitor_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'visitor_type', must be one of '%s'",
                $this->container['visitor_type'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['country']) && (mb_strlen($this->container['country']) > 2)) {
            $invalidProperties[] = "invalid value for 'country', the character length must be smaller than or equal to 2.";
        }

        if (!is_null($this->container['country']) && (mb_strlen($this->container['country']) < 2)) {
            $invalidProperties[] = "invalid value for 'country', the character length must be bigger than or equal to 2.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets browser
     *
     * @return string|null
     */
    public function getBrowser()
    {
        return $this->container['browser'];
    }

    /**
     * Sets browser
     *
     * @param string|null $browser Browser used:   IE - Internet Explorer   CH - Chrome   FF - Firefox   OP - Opera   SF - Safari   OTH - Other
     *
     * @return self
     */
    public function setBrowser($browser)
    {
        if (is_null($browser)) {
            throw new \InvalidArgumentException('non-nullable browser cannot be null');
        }
        $allowedValues = $this->getBrowserAllowableValues();
        if (!in_array($browser, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'browser', must be one of '%s'",
                    $browser,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['browser'] = $browser;

        return $this;
    }

    /**
     * Gets devices
     *
     * @return string[]|null
     */
    public function getDevices()
    {
        return $this->container['devices'];
    }

    /**
     * Sets devices
     *
     * @param string[]|null $devices List of device classes that the visitor device falls into
     *
     * @return self
     */
    public function setDevices($devices)
    {
        if (is_null($devices)) {
            throw new \InvalidArgumentException('non-nullable devices cannot be null');
        }
        $allowedValues = $this->getDevicesAllowableValues();
        if (array_diff($devices, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'devices', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['devices'] = $devices;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string|null
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string|null $source Traffic source
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }
        $allowedValues = $this->getSourceAllowableValues();
        if (!in_array($source, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'source', must be one of '%s'",
                    $source,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets campaign
     *
     * @return string|null
     */
    public function getCampaign()
    {
        return $this->container['campaign'];
    }

    /**
     * Sets campaign
     *
     * @param string|null $campaign Campaign string
     *
     * @return self
     */
    public function setCampaign($campaign)
    {
        if (is_null($campaign)) {
            throw new \InvalidArgumentException('non-nullable campaign cannot be null');
        }
        $this->container['campaign'] = $campaign;

        return $this;
    }

    /**
     * Gets visitor_type
     *
     * @return string|null
     */
    public function getVisitorType()
    {
        return $this->container['visitor_type'];
    }

    /**
     * Sets visitor_type
     *
     * @param string|null $visitor_type Type of the visitor
     *
     * @return self
     */
    public function setVisitorType($visitor_type)
    {
        if (is_null($visitor_type)) {
            throw new \InvalidArgumentException('non-nullable visitor_type cannot be null');
        }
        $allowedValues = $this->getVisitorTypeAllowableValues();
        if (!in_array($visitor_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'visitor_type', must be one of '%s'",
                    $visitor_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['visitor_type'] = $visitor_type;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country Two ISO country code for visitor's country
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            throw new \InvalidArgumentException('non-nullable country cannot be null');
        }
        if ((mb_strlen($country) > 2)) {
            throw new \InvalidArgumentException('invalid length for $country when calling VisitorSegments., must be smaller than or equal to 2.');
        }
        if ((mb_strlen($country) < 2)) {
            throw new \InvalidArgumentException('invalid length for $country when calling VisitorSegments., must be bigger than or equal to 2.');
        }

        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets custom_segments
     *
     * @return string[]|null
     */
    public function getCustomSegments()
    {
        return $this->container['custom_segments'];
    }

    /**
     * Sets custom_segments
     *
     * @param string[]|null $custom_segments Custom Segments as defined inside Convert app. This will be the list of segments' IDs
     *
     * @return self
     */
    public function setCustomSegments($custom_segments)
    {
        if (is_null($custom_segments)) {
            throw new \InvalidArgumentException('non-nullable custom_segments cannot be null');
        }
        $this->container['custom_segments'] = $custom_segments;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


